server:
  port: 8989
  servlet:
    context-path: /cmfz
    jsp:
      init-parameters:
        development: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmfz
    username: root
    password: 1234
  mvc:
    view:
      prefix: /
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 200MB

  activemq:
    broker-url:
  jackson:
    date-format: yyyy-MM-dd
mybatis:
  type-aliases-package: com.baizhi.entity
  mapper-locations: classpath:mapper/*Mapper.xml
